services:
  app-react-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-react-admin
    ports:
      - "80:80"
    networks:
      - app-network
    cpus: '1'
    mem_limit: 1024m

networks:
  app-network:
    name: app_network_default
    external: true
